set echo on
DROP TABLE ACCOUNT_TYPE;
DROP TABLE ACCOUNT_TRANSACTION;


CREATE TABLE ACCOUNT_TYPE
(
    ACCOUNT_TYPE_ID number(15) NOT NULL,
    MNEMONIC varchar2(50) NOT NULL,
    ACCOUNT_TYPE_NAME varchar2(50) NOT NULL,
    CREATION_DATE date NOT NULL,
    CONSTRAINT pk_ACCOUNT_TYPE_ID primary key (ACCOUNT_TYPE_ID)
);

CREATE TABLE ACCOUNT_TRANSACTION
(
    ACCOUNT_TRANSACTION_ID number(15) NOT NULL,
    ACCOUNT_TYPE_ID number(15) NOT NULL,
    MEMBER_ID number(15) NOT NULL,
    AMOUNT number(4) NOT NULL,
    TRANSACTION_DATE date NOT NULL,
    CONSTRAINT pk_ACCOUNT_TRANSACTION_ID primary key (ACCOUNT_TRANSACTION_ID),
    CONSTRAINT fk_ACCOUNT_TYPE_ID foreign key (ACCOUNT_TYPE_ID)
        REFERENCES ACCOUNT_TYPE(ACCOUNT_TYPE_ID) ON DELETE SET NULL
);
COMMIT;
SET echo OFF